### ISSUE TITLE
Prediction fails

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Rivers#15]
When I try to run `predict.py`, I am getting the following errors from Tensorflow:
```
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 3 and 32. Shapes are [3,3,3,32] and [32,8,3,3]. for 'Assign' (op: 'Assign') with input shapes: [3,3,3,32], [32,8,3,3].
```

The image I used was `WV02_12JUL181553195-3bands-356.tif` and the latest weights available to me.

To run on Bridges:
```
module load anaconda3/2019.03
source activate keras-gpu
python3 predict.py --input test_folder/WV02_12JUL181553195-3bands-356-multipage.tif --output_folder test_predict/
```

**Comment by iparask** [comment]
Hello @samiradaneshgar and @bspitzbart ,

I copied `predict.py` from Samira's folders and also used a multipage image from her directory. I still get the same error:
```
(keras-gpu) [paraskev@gpu035 rivers_unit]$ cp /pylon5/mc3bggp/sda10738/Rivers/src/training/predict.py .
(keras-gpu) [paraskev@gpu035 rivers_unit]$ python3 predict.py --input /pylon5/mc3bggp/sda10738/Rivers/src/training/3Band-WV-Multipage/WV02_12JUL181553195-3bands-356-multipage.tif -w weights/unet_weights.hdf5
Using TensorFlow backend.
WARNING:tensorflow:From /opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2020-02-21 14:23:53.623642: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-02-21 14:23:53.639445: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2095195000 Hz
2020-02-21 14:23:53.647503: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56049e435610 executing computations on platform Host. Devices:
2020-02-21 14:23:53.647566: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-02-21 14:23:53.891985: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56049e4f3d60 executing computations on platform CUDA. Devices:
2020-02-21 14:23:53.892030: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-21 14:23:53.892041: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (1): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-02-21 14:23:53.892640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:81:00.0
totalMemory: 15.90GiB freeMemory: 15.64GiB
2020-02-21 14:23:53.892723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:87:00.0
totalMemory: 15.90GiB freeMemory: 15.64GiB
2020-02-21 14:23:53.894310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1
2020-02-21 14:23:53.897565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-21 14:23:53.897584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1
2020-02-21 14:23:53.897593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N Y
2020-02-21 14:23:53.897600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   Y N
2020-02-21 14:23:53.897789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15216 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:81:00.0, compute capability: 6.0)
2020-02-21 14:23:53.898700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15216 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:87:00.0, compute capability: 6.0)
WARNING:tensorflow:From /opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 3 and 32. Shapes are [3,3,3,32] and [32,8,3,3]. for 'Assign' (op: 'Assign') with input shapes: [3,3,3,32], [32,8,3,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 103, in <module>
    main()
  File "predict.py", line 71, in main
    model.load_weights(args.weights_path)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1762, in assign
    name=name)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/opt/packages/anaconda/anaconda3-2019.03/envs/keras-gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 3 and 32. Shapes are [3,3,3,32] and [32,8,3,3]. for 'Assign' (op: 'Assign') with input shapes: [3,3,3,32], [32,8,3,3].
```

It seems to me like a model error. @samiradaneshgar can you point me to a weights file on Bridges that I can use?

**Comment by samiraucsb** [comment]
Hi @iparask ,
Do you have gen_patches.py, train_unet.py, and unet_model.py in the same folder as predict.py?

**Comment by samiraucsb** [comment]
Here is the weights path on Bridges:
/home/sda10738/pylon5/Rivers/src/training/weights/unet_weights.hdf5

**Comment by iparask** [comment]
Hello @samiradaneshgar ,
> Hi @iparask ,
> Do you have gen_patches.py, train_unet.py, and unet_model.py in the same folder as predict.py?

Yes, I do. I will check again tomorrow.

**Comment by iparask** [comment]
Okay! Apparently it was the weights. I'm able to run the prediction and I am closing this issue.
