### ISSUE TITLE
iceberg_rivers.mosaic fails with `invalid literal for int() with base 10: 'rivers_out3869'`

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/Rivers#19]
```
iceberg_rivers.mosaic -i /pylon5/mc3bggp/aymen/rivers_out/ -iw /pylon5/mc3bggp/sda10738/New/8Bands_WV/WV02_20150714152221_8bands.tif -t 224 -s 112 -o m
osaic_output/
Traceback (most recent call last):
  File "/home/aymen/.local/bin/iceberg_rivers.mosaic", line 28, in <module>
    args.input_WV, args.tile_size)
  File "/home/aymen/.local/lib/python3.5/site-packages/iceberg_rivers/search/mosaic/mosaic_unet.py", line 31, in mosaic_unet
    list = sorted(os.listdir(masks_path),key=lambda x: int(os.path.splitext(x)[0]))
  File "/home/aymen/.local/lib/python3.5/site-packages/iceberg_rivers/search/mosaic/mosaic_unet.py", line 31, in <lambda>
    list = sorted(os.listdir(masks_path),key=lambda x: int(os.path.splitext(x)[0]))
ValueError: invalid literal for int() with base 10: 'rivers_out3869'
```

**Comment by iparask** [comment]
Resolved
