### ISSUE TITLE
Python environment issue

### ISSUE THREAD

**Issue by samiraucsb** [iceberg-project/Rivers#21]
Here is the environment in which I run the codes:

```bash
cd $PROJECT/Rivers2               # make sure you are in the same directory where everything was set up before.
module load AI/anaconda3-tf1.2020.11
export PATH=/ocean/projects/mcb110096p/paraskev/gdal-3.0.4/bin:$PATH
export LD_LIBRARY_PATH=/ocean/projects/mcb110096p/paraskev/gdal-3.0.4/lib:$LD_LIBRARY_PATH
export GDAL_DATA=/ocean/projects/mcb110096p/paraskev/gdal-3.0.4/share/gdal
source activate iceberg_rivers/    # activate your environment, no need to create a new environment because the Rivers tools are
installed and isolated here.
export PYTHONPATH=/ocean/projects/mcb110096p/sda10738/iceberg_rivers/lib/python3.7/site-packages/

However, I receive the following error now:

Using TensorFlow backend.
Traceback (most recent call last):
  File "predict_unet.py", line 11, in <module>
    from osgeo import gdal
  File "/ocean/projects/mcb110096p/sda10738/Rivers2/iceberg_rivers/lib/python3.7/site-packages/osgeo/__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "/ocean/projects/mcb110096p/sda10738/Rivers2/iceberg_rivers/lib/python3.7/site-packages/osgeo/__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/ocean/projects/mcb110096p/sda10738/Rivers2/iceberg_rivers/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/ocean/projects/mcb110096p/sda10738/Rivers2/iceberg_rivers/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b```

**Comment by AymenFJA** [comment]
Update: I can replicate the issue above and it is related to an updated system library (does not exist anymore on Bridges2 Fedora OS), currently working on finding an alternative way to install `GDAL`.

**Comment by AymenFJA** [comment]
Update: the issue is a conflict between the default system shared libraries and Conda shared libraries. Conda seems to prefer the `system default shared libraries ` under `/lib64/` instead of using the installed `/conda/lib` that is needed for `GDAL` to run. Thus, exporting `Conda` `libs` solved the problem as shown below:
```bash
(/iceberg_rivers) [aymen@bridges2-login011 aymen]$ export LD_LIBRARY_PATH=/ocean/projects/mcb110096p/aymen/anaconda3/lib
(/iceberg_rivers) [aymen@bridges2-login011 aymen]$ iceberg_rivers.tiling --help
usage: iceberg_rivers.tiling [-h] [-i INPUT] [-t TILE_SIZE] [-s STEP]
                             [-o OUTPUT]

divides a WorldView image into tiles

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        Path and name of the WorldView image
  -t TILE_SIZE, --tile_size TILE_SIZE
                        Tile size
  -s STEP, --step STEP  Step size
  -o OUTPUT, --output OUTPUT
                        Folder where output tiles will be stored
(/iceberg_rivers) [aymen@bridges2-login011 aymen]$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>>
```

 @samiradaneshgar: can you please run this command before you run the `iceberg.rivers` command in your shell and confirm if it is working now?:

```bash
export LD_LIBRARY_PATH=/ocean/projects/mcb110096p/sda10738/anaconda3/lib
```

Or in @samiradaneshgar situation the path was: 
```bash
export LD_LIBRARY_PATH=/opt/packages/anaconda3/lib
```

**Comment by samiraucsb** [comment]
The issue has been resolved. Thanks!
